name: Docker Build and Push

on:
  push:
    branches:
      - "main"
  release:
    types: [published]

env:
  IMAGE_REGISTRY: quay.io
  IMAGE_NAMESPACE: andreygubarev
  IMAGE_NAME: headscale

jobs:
  build:
    name: Build and push multi-arch image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platforms: [linux/amd64, linux/arm64]

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Determine tags
        id: get_tags
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            echo ::set-output name=TAG::"$VERSION"
          else
            echo ::set-output name=TAG::"latest"
          fi

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          platforms: ${{ matrix.platforms }}
          tags: ghcr.io/${{ github.repository }}:${{ steps.get_tags.outputs.TAG }}
